# General parameters for the planner node
replan_pos_threshold: 0.25
replan_yaw_threshold: 0.15

max_new_segments: 0
min_new_segments: 0
max_new_tries: 0
min_new_tries: 0
min_new_value: 0

# Verbosity and visualization
verbose: true
verbose_modules: true
build_modules_on_init: true
visualize: true
highlight_executed_trajectory: true

# Specify a map representation
map:
  type: "FiestaMap"
  resolution: 0.08
  update_esdf_every_n_sec: 0.2
  reserved_size: 1000000
  # lx: -5.0
  # ly: -5.0 ESDF DOESNT WORK AS GOOD WITH A SMALLER MAP SIZE WTF
  # lz: -1.5
  # rx: 20
  # ry: 20
  # rz: 5
  lx: -10.0
  ly: -22.0
  lz: -1.5
  rx: 40
  ry: 40
  rz: 15
  min_ray_length: 0.0 # originally 0.5
  max_ray_length: 5.0
  ray_cast_num_thread: 0
  p_hit: 0.7
  p_miss: 0.35
  p_min: 0.12
  p_max: 0.97 
  p_occ: 0.80 
  global_map: true
  global_update: true
  global_vis: true
  radius_x: 3.0
  radius_y: 3.0 
  radius_z: 1.5
  use_depth_filter: true
  depth_filter_tolerance: 0.1
  depth_filter_max_dist: 10.0
  depth_filter_min_dist: 0.1
  depth_filter_margin: 0
  visualize_every_n_updates: 10
  slice_vis_max_dist: 2.0 
  slice_vis_level: 1.6 
  vis_lower_bound: 0 
  vis_upper_bound: 10

# System constraints
system_constraints:
  # v_max: 1.0
  # a_max: 1.0
  # yaw_rate_max: 1.6
  # yaw_accel_max: 1.6
  # collision_radius: 0.1
  v_max: 1.0
  a_max: 1.0
  yaw_rate_max: 0.8
  yaw_accel_max: 0.8
  collision_radius: 0.35

# Specifying a trajectory generator
trajectory_generator:
  type: "Uniform"
  collision_optimistic: false
  bounding_volume_args: "/map_bounding_volume"

  # Generator Params
  n_segments: 5
  distance: 1.5
  yaw_angle: 1.2
  ascent_angle: 0.523
  sampling_rate: 20

  # Expansion site selection policy
  segment_selector:
    type: "RandomWeighted"
    revisit: false
    factor: 2.0
    leaf_probability: 1.0
    uniform_probability: 0.2

  # Generator Update step
  generator_updater:
    type: "RecheckCollision"

# Specifying a trajectory evaluator
trajectory_evaluator:
  type: "NaiveEvaluator"

  # Evaluator params and sensor model for simulated sensor evaluators
  clear_from_parents: false
  camera_params_ns: "/unreal/unreal_ros_client/camera_params"
  visualize_sensor_view: true
  bounding_volume_args: "/target_bounding_volume"
  sensor_model:
    type: "IterativeRayCaster"
    sampling_time: 0.0
    ray_length: 5.0
    focal_length: 320 #518.8579 #320 with field of view of 90, 518.8579 WITH SSC with field of view of 50.967800
    resolution_x: 640
    resolution_y: 480
    downsampling_factor: 3.0

  # Choose a cost
  cost_computer:
    type: "SegmentTime"

  # How to compute the values
  value_computer:
    type: "AccumulateValue"
    following_value_computer:
      type: "LinearValue"
      cost_weight: 1.0
      gain_weight: 0.1

  # Execution policy for available segments
  next_selector:
    type: "SubsequentBest"

  # Evaluator Update step
  evaluator_updater:
    type: "UpdateAll"
    update_gain: false
    update_cost: false
    update_value: true

# Specify a backtracker if the planner gets stuck
back_tracker:
  type: "RotateReverse"
  turn_rate: 0.8 # originally 0.8
  update_rate: 2.0
  sampling_rate: 20.0
  n_rotations: 1
  stack_size: 10
